### ISSUE TITLE
Mastermind.rb

### ISSUE THREAD

**Issue by Willardgmoore** [rglassett/appacademy#1]
I found that appacademy/w1/w1d3/mastermind/mastermind.rb doesn't ever let you win. I'm not sure if the file exists for teaching purposes and that's why it doesn't run right or not. I'm not sure, I was looking around hoping to prepare myself better for your entrance test. I've determined that it won't let you win by adding         puts "Answer #{sequence[el]} vs User #{@user_guess[el]}" #Testing purposes only  
just below line 25 as a new line 26. I haven't the slightest idea where to begin to fix it, but I would hope that it's not expected of me just yet as I'm studying to take the entrance test. At any rate, thanks for the great help you have been to me through all of the preparation material you've made available.

**Comment by rglassett** [comment]
Thanks for raising the issue! This is just my personal work from my time as an App Academy student, and not actually intended to serve as preparatory material. Nonetheless, I'm glad you've found it helpful and I will certainly look into the bug you're describing.

**Comment by rglassett** [comment]
Looks like I refactored Mastermind a while ago but forgot to upload. The game should be winnable now, as of be63e57790e276671f33f4a0ff0cb6dc5225afb0. Thanks again for the note!

**Comment by Willardgmoore** [comment]
It looks like a whole brand new piece of code. I'm glad to see that I'm not the only one that changes a lot between revisions. The code looks great now. It's hard to believe that's the level of coding I would be working on, on day 3. I haven't taken the coding challenge to apply yet, knowing they only accept the top 5% and seeing the level of coding on this problem, it only makes me hesitant to apply for fear of losing the opportunity. I'm happy you made it. Keep living the dream.
